// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-155-Gx7tO09-VL0RoXBMV9VAauQZMM',
    appId: '1:323570209857:web:99ddc11e682d1bb77862c0',
    messagingSenderId: '323570209857',
    projectId: 'yolog-781c1',
    authDomain: 'yolog-781c1.firebaseapp.com',
    storageBucket: 'yolog-781c1.firebasestorage.app',
    measurementId: 'G-KHVGJQMTKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGPGpb-0s7kNR9wiWX3ldE5PZXKCXg_s',
    appId: '1:323570209857:android:4d2647a96ac71de87862c0',
    messagingSenderId: '323570209857',
    projectId: 'yolog-781c1',
    storageBucket: 'yolog-781c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4lZTO2RE6q0qyP_rdO4hZ_tedmTTJgBk',
    appId: '1:323570209857:ios:4f363cd4963af2ec7862c0',
    messagingSenderId: '323570209857',
    projectId: 'yolog-781c1',
    storageBucket: 'yolog-781c1.firebasestorage.app',
    iosClientId: '323570209857-suq4s0umu4jradjsiu728qlt9ok85qiq.apps.googleusercontent.com',
    iosBundleId: 'com.yolog.yolog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4lZTO2RE6q0qyP_rdO4hZ_tedmTTJgBk',
    appId: '1:323570209857:ios:4f363cd4963af2ec7862c0',
    messagingSenderId: '323570209857',
    projectId: 'yolog-781c1',
    storageBucket: 'yolog-781c1.firebasestorage.app',
    iosClientId: '323570209857-suq4s0umu4jradjsiu728qlt9ok85qiq.apps.googleusercontent.com',
    iosBundleId: 'com.yolog.yolog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj-155-Gx7tO09-VL0RoXBMV9VAauQZMM',
    appId: '1:323570209857:web:f9e538c82ceda3107862c0',
    messagingSenderId: '323570209857',
    projectId: 'yolog-781c1',
    authDomain: 'yolog-781c1.firebaseapp.com',
    storageBucket: 'yolog-781c1.firebasestorage.app',
    measurementId: 'G-J19TFGQSCH',
  );
}
